version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: musique

  musique-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musique-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/musique
    depends_on:
      - mongodb
